services:
  solismqtt:
    container_name: solismqtt
    build: .
#    depends_on:
#      - mosquitto
#      - homeassistant
    volumes:
      - './configuration.yaml:/app/configuration.yaml'
      - '/etc/localtime:/etc/localtime:ro'

